import type { Metadata } from "next";
import { JetBrains_Mono, Raleway } from "next/font/google";
import "./globals.css";

const jbSans = JetBrains_Mono({
  variable: "--font-jb-sans",
  subsets: ["latin"],
});

const ralewaySans = Raleway({
  variable: "--font-raleway-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jbSans.variable} ${ralewaySans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
